export const courses = [
    {
      id: 1,
      name: "Bca",
      imgUrl: "monkey",
      link: "/videos",
      description: "videos lesson",
    },
    {
      id: 2,
      name: "BBA",
      imgUrl: "/imgUrl",
      link: "/study",
      description: "videos lesson",
    },
    {
      id: 3,
      name: "bcom",
      imgUrl: "/imgUrl",
      link: "/videos",
      description: "videos lesson",
    },
    {
      id: 4,
      name: "mcom",
      imgUrl: "/imgUrl",
      link: "/videos",
      description: "videos lesson",
    },
    {
      id: 5,
      name: "Bca",
      imgUrl: "monkey",
      link: "/videos",
      description: "videos lesson",
    },
    {
      id: 6,
      name: "BBA",
      imgUrl: "/imgUrl",
      link: "/study",
      description: "videos lesson",
    },
    {
      id: 7,
      name: "bcom",
      imgUrl: "/imgUrl",
      link: "/videos",
      description: "videos lesson",
    },
    {
      id: 8,
      name: "ba english",
      imgUrl: "/imgUrl",
      link: "/videos",
      description: "videos lesson",
    },
    {
      id: 9,
      name: "Bca",
      imgUrl: "monkey",
      link: "/videos",
      description: "videos lesson",
    },
    {
      id: 10,
      name: "BBA",
      imgUrl: "/imgUrl",
      link: "/study",
      description: "videos lesson",
    },
    {
      id: 11,
      name: "bcom",
      imgUrl: "/imgUrl",
      link: "/videos",
      description: "videos lesson",
    },
    {
      id: 12,
      name: "ba arabic",
      imgUrl: "/imgUrl",
      link: "/videos",
      description: "videos lesson",
    },
  ];
  