export const courses = [
    {
      id: 1,
      name: "Bca",
      img: "monkey",
      link: "/videos",
      descrition: "videos lesson",
    },
    {
      id: 2,
      name: "BBA",
      img: "/img",
      link: "/study",
      descrition: "videos lesson",
    },
    {
      id: 3,
      name: "bcom",
      img: "/img",
      link: "/videos",
      descrition: "videos lesson",
    },
    {
      id: 4,
      name: "mcom",
      img: "/img",
      link: "/videos",
      descrition: "videos lesson",
    },
    {
      id: 1,
      name: "Bca",
      img: "monkey",
      link: "/videos",
      descrition: "videos lesson",
    },
    {
      id: 2,
      name: "BBA",
      img: "/img",
      link: "/study",
      descrition: "videos lesson",
    },
    {
      id: 3,
      name: "bcom",
      img: "/img",
      link: "/videos",
      descrition: "videos lesson",
    },
    {
      id: 4,
      name: "ba english",
      img: "/img",
      link: "/videos",
      descrition: "videos lesson",
    },
    {
      id: 1,
      name: "Bca",
      img: "monkey",
      link: "/videos",
      descrition: "videos lesson",
    },
    {
      id: 2,
      name: "BBA",
      img: "/img",
      link: "/study",
      descrition: "videos lesson",
    },
    {
      id: 3,
      name: "bcom",
      img: "/img",
      link: "/videos",
      descrition: "videos lesson",
    },
    {
      id: 4,
      name: "ba arabic",
      img: "/img",
      link: "/videos",
      descrition: "videos lesson",
    },
  ];
  